# Part 1

finding **pairs of scanners** that have overlapping detection regions such that there are **at least 12** beacons that both scanners detect within the overlap. By establishing 12 common beacons, you can precisely determine where the scanners are relative to each other, allowing you to reconstruct the beacon map one scanner at a time.

In total, **each scanner could be in any of 24 different orientations**: facing positive or negative x, y, or z, and considering any of four directions "up" from that facing.

**all "absolute" positions will be expressed relative to scanner 0** (using the orientation of scanner 0 and as if scanner 0 is at coordinates 0,0,0).

### Julia's notes

* Find pairs with overlapping beacons
* Drop dupes in the the overlapped beacons (we are essentially double counting them)

... For part 1, we just need to count total number of beacons, so we're done. Bets on part 2 requiring their absolute locations?

* Find what that means about the location of the scanners (so does this mean we start with scanner 0 + its pair, get that orientation and keep going?)


## Playground

In [39]:
# https://www.kite.com/python/docs/scipy.spatial.transform.Rotation.from_rotvec
import scipy
import numpy as np
from scipy.spatial.transform import Rotation as R
from itertools import combinations


In [71]:
def generate_rotations():
    
    rotations = []
    rotation_axes = []
    
    for i in range(1,4):
        rotations = rotations + (list(combinations([0,1,2],i)))
    
    for rotation in rotations:
    
        rotation_axis = np.zeros(3)
        for r in rotation:
            
            for sign in [1,-1]:
                rotation_axis[r] = sign
                rotation_axes.append(rotation_axis)
    
    return rotation_axes

In [98]:
generate_rotations()

[array([-1.,  0.,  0.]),
 array([-1.,  0.,  0.]),
 array([ 0., -1.,  0.]),
 array([ 0., -1.,  0.]),
 array([ 0.,  0., -1.]),
 array([ 0.,  0., -1.]),
 array([-1., -1.,  0.]),
 array([-1., -1.,  0.]),
 array([-1., -1.,  0.]),
 array([-1., -1.,  0.]),
 array([-1.,  0., -1.]),
 array([-1.,  0., -1.]),
 array([-1.,  0., -1.]),
 array([-1.,  0., -1.]),
 array([ 0., -1., -1.]),
 array([ 0., -1., -1.]),
 array([ 0., -1., -1.]),
 array([ 0., -1., -1.]),
 array([-1., -1., -1.]),
 array([-1., -1., -1.]),
 array([-1., -1., -1.]),
 array([-1., -1., -1.]),
 array([-1., -1., -1.]),
 array([-1., -1., -1.])]

In [96]:
r = R.from_rotvec(270 * np.array([1, 1, 0]), degrees=True)
r.as_rotvec(degrees=True)

array([15.44155877, 15.44155877,  0.        ])

In [91]:

def rotations(vec):

    i = 1
#     print(i)
    print(vec)
    print()
    
    axes = generate_rotations()
    degs = [90,180, 270]
    
    for rotation_axis in axes:
#         print(rotation_axis)
        for deg in degs:
            rotation_degrees = deg
            print(rotation_degrees)
            print(rotation_axis)
#             rotation_radians = np.radians(rotation_degrees)

            rotation_vector = rotation_degrees * rotation_axis
            print(rotation_vector)
            rotation = R.from_rotvec(rotation_vector,True)
            rotated_vec = rotation.apply(vec)

            i+=1
#             print(i)
#             print([int(item) for item in rotated_vec])
            print()

In [92]:
rotations([-618,-824,-621])

[-618, -824, -621]

90
[-1.  0.  0.]
[-90.   0.   0.]

180
[-1.  0.  0.]
[-180.    0.    0.]

270
[-1.  0.  0.]
[-270.    0.    0.]

90
[-1.  0.  0.]
[-90.   0.   0.]

180
[-1.  0.  0.]
[-180.    0.    0.]

270
[-1.  0.  0.]
[-270.    0.    0.]

90
[ 0. -1.  0.]
[  0. -90.   0.]

180
[ 0. -1.  0.]
[   0. -180.    0.]

270
[ 0. -1.  0.]
[   0. -270.    0.]

90
[ 0. -1.  0.]
[  0. -90.   0.]

180
[ 0. -1.  0.]
[   0. -180.    0.]

270
[ 0. -1.  0.]
[   0. -270.    0.]

90
[ 0.  0. -1.]
[  0.   0. -90.]

180
[ 0.  0. -1.]
[   0.    0. -180.]

270
[ 0.  0. -1.]
[   0.    0. -270.]

90
[ 0.  0. -1.]
[  0.   0. -90.]

180
[ 0.  0. -1.]
[   0.    0. -180.]

270
[ 0.  0. -1.]
[   0.    0. -270.]

90
[-1. -1.  0.]
[-90. -90.   0.]

180
[-1. -1.  0.]
[-180. -180.    0.]

270
[-1. -1.  0.]
[-270. -270.    0.]

90
[-1. -1.  0.]
[-90. -90.   0.]

180
[-1. -1.  0.]
[-180. -180.    0.]

270
[-1. -1.  0.]
[-270. -270.    0.]

90
[-1. -1.  0.]
[-90. -90.   0.]

180
[-1. -1.  0.]
[-180. -180.    0.]

27